services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: automation-core-rust
    restart: unless-stopped
    env_file:
      - .env
    mem_limit: 15m
    memswap_limit: 15m
    cpus: "0.10"